from enum import StrEnum


class WorkflowState(StrEnum):
    CREATOR_LEAD = "CREATOR_LEAD"
    RIGHTS_PENDING = "RIGHTS_PENDING"
    RIGHTS_APPROVED = "RIGHTS_APPROVED"
    SOURCE_REQUESTED = "SOURCE_REQUESTED"
    SOURCE_UPLOADED = "SOURCE_UPLOADED"
    SOURCE_VALIDATED = "SOURCE_VALIDATED"
    ANALYSIS_RUNNING = "ANALYSIS_RUNNING"
    AD_REVIEW_REQUIRED = "AD_REVIEW_REQUIRED"
    TRANSLATION_RUNNING = "TRANSLATION_RUNNING"
    TRANSLATION_REVIEW = "TRANSLATION_REVIEW"
    DUBBING_RUNNING = "DUBBING_RUNNING"
    AUDIO_REVIEW = "AUDIO_REVIEW"
    RENDER_RUNNING = "RENDER_RUNNING"
    INTERNAL_QA = "INTERNAL_QA"
    CREATOR_REVIEW = "CREATOR_REVIEW"
    PUBLISH_READY = "PUBLISH_READY"
    UPLOADED_PRIVATE = "UPLOADED_PRIVATE"
    PLATFORM_CHECK = "PLATFORM_CHECK"
    PUBLISHED = "PUBLISHED"
    PERFORMANCE_REVIEW = "PERFORMANCE_REVIEW"
    ARCHIVED = "ARCHIVED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RIGHTS_REVOKED = "RIGHTS_REVOKED"


class WorkflowEvent(StrEnum):
    REQUEST_RIGHTS = "REQUEST_RIGHTS"
    APPROVE_RIGHTS = "APPROVE_RIGHTS"
    REQUEST_SOURCE = "REQUEST_SOURCE"
    RECORD_SOURCE_UPLOAD = "RECORD_SOURCE_UPLOAD"
    VALIDATE_SOURCE = "VALIDATE_SOURCE"
    START_ANALYSIS = "START_ANALYSIS"
    REQUIRE_AD_REVIEW = "REQUIRE_AD_REVIEW"
    START_TRANSLATION = "START_TRANSLATION"
    REQUEST_TRANSLATION_REVIEW = "REQUEST_TRANSLATION_REVIEW"
    START_DUBBING = "START_DUBBING"
    REQUEST_AUDIO_REVIEW = "REQUEST_AUDIO_REVIEW"
    START_RENDER = "START_RENDER"
    REQUEST_INTERNAL_QA = "REQUEST_INTERNAL_QA"
    REQUEST_CREATOR_REVIEW = "REQUEST_CREATOR_REVIEW"
    MARK_PUBLISH_READY = "MARK_PUBLISH_READY"
    UPLOAD_PRIVATE = "UPLOAD_PRIVATE"
    COMPLETE_PLATFORM_CHECK = "COMPLETE_PLATFORM_CHECK"
    PUBLISH_APPROVED = "PUBLISH_APPROVED"
    START_PERFORMANCE_REVIEW = "START_PERFORMANCE_REVIEW"
    ARCHIVE = "ARCHIVE"
    BLOCK = "BLOCK"
    FAIL = "FAIL"
    RESUME = "RESUME"
    RETRY = "RETRY"
    CANCEL = "CANCEL"
    REVOKE_RIGHTS = "REVOKE_RIGHTS"


class TaskGroup(StrEnum):
    ANALYSIS = "analysis"
    TRANSLATION = "translation"
    DUBBING = "dubbing"
    AUDIO = "audio"
    RENDER = "render"
    SHORTS = "shorts"
    PUBLISHING = "publishing"
    ANALYTICS = "analytics"
    NOTIFICATIONS = "notifications"


class TaskRunStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
    DEAD_LETTERED = "dead_lettered"


class IdempotencyStatus(StrEnum):
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class DeadLetterStatus(StrEnum):
    PENDING = "pending"
    REPLAYED = "replayed"
    DISCARDED = "discarded"
